name: whisp_diary
description: A secure diary app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  image_picker: ^0.8.9
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_auth: ^2.1.6
  path_provider: ^2.0.15
  riverpod_annotation: ^2.1.1
  table_calendar: ^3.0.9
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
